export type CountryReligion = "Christianity" | "Islam" | "Hinduism" | "Buddhism" | "Judaism" | "Folk/Traditional" | "Unaffiliated" | "Mixed";
export type CountryGovernment = "Republic" | "Federal republic" | "Constitutional monarchy" | "Monarchy" | "One-party state" | "Theocracy" | "Military junta";

export interface CountryFact {
  code: string;
  iso2: string;
  name: string;
  continent: string;
  region: string;
  population: number;
  landlocked: boolean;
  areaKm2: number;
  religion: CountryReligion;
  government: CountryGovernment;
}

// Objective fields come from mledoze/countries plus samayo/country-json. Religion/government are broad gameplay buckets.
export const COUNTRIES = [
  {
    "code": "AFG",
    "iso2": "AF",
    "name": "Afghanistan",
    "continent": "Asia",
    "region": "Southern Asia",
    "population": 37172386,
    "landlocked": true,
    "areaKm2": 652090,
    "religion": "Islam",
    "government": "Republic"
  },
  {
    "code": "ALB",
    "iso2": "AL",
    "name": "Albania",
    "continent": "Europe",
    "region": "Southeast Europe",
    "population": 2866376,
    "landlocked": false,
    "areaKm2": 28748,
    "religion": "Islam",
    "government": "Republic"
  },
  {
    "code": "DZA",
    "iso2": "DZ",
    "name": "Algeria",
    "continent": "Africa",
    "region": "Northern Africa",
    "population": 42228429,
    "landlocked": false,
    "areaKm2": 2381741,
    "religion": "Islam",
    "government": "Republic"
  },
  {
    "code": "AND",
    "iso2": "AD",
    "name": "Andorra",
    "continent": "Europe",
    "region": "Southern Europe",
    "population": 77006,
    "landlocked": true,
    "areaKm2": 468,
    "religion": "Christianity",
    "government": "Republic"
  },
  {
    "code": "AGO",
    "iso2": "AO",
    "name": "Angola",
    "continent": "Africa",
    "region": "Middle Africa",
    "population": 30809762,
    "landlocked": false,
    "areaKm2": 1246700,
    "religion": "Christianity",
    "government": "Republic"
  },
  {
    "code": "ATG",
    "iso2": "AG",
    "name": "Antigua and Barbuda",
    "continent": "Americas",
    "region": "Caribbean",
    "population": 96286,
    "landlocked": false,
    "areaKm2": 442,
    "religion": "Christianity",
    "government": "Constitutional monarchy"
  },
  {
    "code": "ARG",
    "iso2": "AR",
    "name": "Argentina",
    "continent": "Americas",
    "region": "South America",
    "population": 44494502,
    "landlocked": false,
    "areaKm2": 2780400,
    "religion": "Christianity",
    "government": "Federal republic"
  },
  {
    "code": "ARM",
    "iso2": "AM",
    "name": "Armenia",
    "continent": "Asia",
    "region": "Western Asia",
    "population": 2951776,
    "landlocked": true,
    "areaKm2": 29800,
    "religion": "Islam",
    "government": "Republic"
  },
  {
    "code": "AUS",
    "iso2": "AU",
    "name": "Australia",
    "continent": "Oceania",
    "region": "Australia and New Zealand",
    "population": 24982688,
    "landlocked": false,
    "areaKm2": 7741220,
    "religion": "Christianity",
    "government": "Constitutional monarchy"
  },
  {
    "code": "AUT",
    "iso2": "AT",
    "name": "Austria",
    "continent": "Europe",
    "region": "Central Europe",
    "population": 8840521,
    "landlocked": true,
    "areaKm2": 83859,
    "religion": "Christianity",
    "government": "Federal republic"
  },
  {
    "code": "AZE",
    "iso2": "AZ",
    "name": "Azerbaijan",
    "continent": "Asia",
    "region": "Western Asia",
    "population": 9939800,
    "landlocked": true,
    "areaKm2": 86600,
    "religion": "Islam",
    "government": "Republic"
  },
  {
    "code": "BHS",
    "iso2": "BS",
    "name": "Bahamas",
    "continent": "Americas",
    "region": "Caribbean",
    "population": 385640,
    "landlocked": false,
    "areaKm2": 13878,
    "religion": "Christianity",
    "government": "Constitutional monarchy"
  },
  {
    "code": "BHR",
    "iso2": "BH",
    "name": "Bahrain",
    "continent": "Asia",
    "region": "Western Asia",
    "population": 1569439,
    "landlocked": false,
    "areaKm2": 694,
    "religion": "Islam",
    "government": "Monarchy"
  },
  {
    "code": "BGD",
    "iso2": "BD",
    "name": "Bangladesh",
    "continent": "Asia",
    "region": "Southern Asia",
    "population": 161356039,
    "landlocked": false,
    "areaKm2": 143998,
    "religion": "Islam",
    "government": "Republic"
  },
  {
    "code": "BRB",
    "iso2": "BB",
    "name": "Barbados",
    "continent": "Americas",
    "region": "Caribbean",
    "population": 286641,
    "landlocked": false,
    "areaKm2": 430,
    "religion": "Christianity",
    "government": "Constitutional monarchy"
  },
  {
    "code": "BLR",
    "iso2": "BY",
    "name": "Belarus",
    "continent": "Europe",
    "region": "Eastern Europe",
    "population": 9483499,
    "landlocked": true,
    "areaKm2": 207600,
    "religion": "Christianity",
    "government": "Republic"
  },
  {
    "code": "BEL",
    "iso2": "BE",
    "name": "Belgium",
    "continent": "Europe",
    "region": "Western Europe",
    "population": 11433256,
    "landlocked": false,
    "areaKm2": 30518,
    "religion": "Christianity",
    "government": "Constitutional monarchy"
  },
  {
    "code": "BLZ",
    "iso2": "BZ",
    "name": "Belize",
    "continent": "Americas",
    "region": "Central America",
    "population": 383071,
    "landlocked": false,
    "areaKm2": 22696,
    "religion": "Christianity",
    "government": "Constitutional monarchy"
  },
  {
    "code": "BEN",
    "iso2": "BJ",
    "name": "Benin",
    "continent": "Africa",
    "region": "Western Africa",
    "population": 11485048,
    "landlocked": false,
    "areaKm2": 112622,
    "religion": "Folk/Traditional",
    "government": "Republic"
  },
  {
    "code": "BTN",
    "iso2": "BT",
    "name": "Bhutan",
    "continent": "Asia",
    "region": "Southern Asia",
    "population": 754394,
    "landlocked": true,
    "areaKm2": 47000,
    "religion": "Buddhism",
    "government": "Monarchy"
  },
  {
    "code": "BOL",
    "iso2": "BO",
    "name": "Bolivia",
    "continent": "Americas",
    "region": "South America",
    "population": 11353142,
    "landlocked": true,
    "areaKm2": 1098581,
    "religion": "Christianity",
    "government": "Republic"
  },
  {
    "code": "BIH",
    "iso2": "BA",
    "name": "Bosnia and Herzegovina",
    "continent": "Europe",
    "region": "Southeast Europe",
    "population": 3323929,
    "landlocked": false,
    "areaKm2": 51197,
    "religion": "Christianity",
    "government": "Federal republic"
  },
  {
    "code": "BWA",
    "iso2": "BW",
    "name": "Botswana",
    "continent": "Africa",
    "region": "Southern Africa",
    "population": 2254126,
    "landlocked": true,
    "areaKm2": 581730,
    "religion": "Christianity",
    "government": "Republic"
  },
  {
    "code": "BRA",
    "iso2": "BR",
    "name": "Brazil",
    "continent": "Americas",
    "region": "South America",
    "population": 209469333,
    "landlocked": false,
    "areaKm2": 8547403,
    "religion": "Christianity",
    "government": "Federal republic"
  },
  {
    "code": "BRN",
    "iso2": "BN",
    "name": "Brunei",
    "continent": "Asia",
    "region": "South-Eastern Asia",
    "population": 428962,
    "landlocked": false,
    "areaKm2": 5765,
    "religion": "Islam",
    "government": "Monarchy"
  },
  {
    "code": "BGR",
    "iso2": "BG",
    "name": "Bulgaria",
    "continent": "Europe",
    "region": "Southeast Europe",
    "population": 7025037,
    "landlocked": false,
    "areaKm2": 110994,
    "religion": "Christianity",
    "government": "Republic"
  },
  {
    "code": "BFA",
    "iso2": "BF",
    "name": "Burkina Faso",
    "continent": "Africa",
    "region": "Western Africa",
    "population": 19751535,
    "landlocked": true,
    "areaKm2": 274000,
    "religion": "Islam",
    "government": "Republic"
  },
  {
    "code": "BDI",
    "iso2": "BI",
    "name": "Burundi",
    "continent": "Africa",
    "region": "Eastern Africa",
    "population": 11175378,
    "landlocked": true,
    "areaKm2": 27834,
    "religion": "Christianity",
    "government": "Republic"
  },
  {
    "code": "KHM",
    "iso2": "KH",
    "name": "Cambodia",
    "continent": "Asia",
    "region": "South-Eastern Asia",
    "population": 16249798,
    "landlocked": false,
    "areaKm2": 181035,
    "religion": "Buddhism",
    "government": "Constitutional monarchy"
  },
  {
    "code": "CMR",
    "iso2": "CM",
    "name": "Cameroon",
    "continent": "Africa",
    "region": "Middle Africa",
    "population": 25216237,
    "landlocked": false,
    "areaKm2": 475442,
    "religion": "Christianity",
    "government": "Republic"
  },
  {
    "code": "CAN",
    "iso2": "CA",
    "name": "Canada",
    "continent": "Americas",
    "region": "North America",
    "population": 37057765,
    "landlocked": false,
    "areaKm2": 9970610,
    "religion": "Christianity",
    "government": "Constitutional monarchy"
  },
  {
    "code": "CPV",
    "iso2": "CV",
    "name": "Cape Verde",
    "continent": "Africa",
    "region": "Western Africa",
    "population": 555987,
    "landlocked": false,
    "areaKm2": 4033,
    "religion": "Christianity",
    "government": "Republic"
  },
  {
    "code": "CAF",
    "iso2": "CF",
    "name": "Central African Republic",
    "continent": "Africa",
    "region": "Middle Africa",
    "population": 4666377,
    "landlocked": true,
    "areaKm2": 622984,
    "religion": "Christianity",
    "government": "Republic"
  },
  {
    "code": "TCD",
    "iso2": "TD",
    "name": "Chad",
    "continent": "Africa",
    "region": "Middle Africa",
    "population": 15477751,
    "landlocked": true,
    "areaKm2": 1284000,
    "religion": "Islam",
    "government": "Republic"
  },
  {
    "code": "CHL",
    "iso2": "CL",
    "name": "Chile",
    "continent": "Americas",
    "region": "South America",
    "population": 18729160,
    "landlocked": false,
    "areaKm2": 756626,
    "religion": "Christianity",
    "government": "Republic"
  },
  {
    "code": "CHN",
    "iso2": "CN",
    "name": "China",
    "continent": "Asia",
    "region": "Eastern Asia",
    "population": 1392730000,
    "landlocked": false,
    "areaKm2": 9572900,
    "religion": "Unaffiliated",
    "government": "One-party state"
  },
  {
    "code": "COL",
    "iso2": "CO",
    "name": "Colombia",
    "continent": "Americas",
    "region": "South America",
    "population": 49648685,
    "landlocked": false,
    "areaKm2": 1138914,
    "religion": "Christianity",
    "government": "Republic"
  },
  {
    "code": "COM",
    "iso2": "KM",
    "name": "Comoros",
    "continent": "Africa",
    "region": "Eastern Africa",
    "population": 832322,
    "landlocked": false,
    "areaKm2": 1862,
    "religion": "Islam",
    "government": "Federal republic"
  },
  {
    "code": "COG",
    "iso2": "CG",
    "name": "Congo",
    "continent": "Africa",
    "region": "Middle Africa",
    "population": 5244363,
    "landlocked": false,
    "areaKm2": 342000,
    "religion": "Christianity",
    "government": "Republic"
  },
  {
    "code": "CRI",
    "iso2": "CR",
    "name": "Costa Rica",
    "continent": "Americas",
    "region": "Central America",
    "population": 4999441,
    "landlocked": false,
    "areaKm2": 51100,
    "religion": "Christianity",
    "government": "Republic"
  },
  {
    "code": "HRV",
    "iso2": "HR",
    "name": "Croatia",
    "continent": "Europe",
    "region": "Southeast Europe",
    "population": 4087843,
    "landlocked": false,
    "areaKm2": 56538,
    "religion": "Christianity",
    "government": "Republic"
  },
  {
    "code": "CUB",
    "iso2": "CU",
    "name": "Cuba",
    "continent": "Americas",
    "region": "Caribbean",
    "population": 11338138,
    "landlocked": false,
    "areaKm2": 110861,
    "religion": "Christianity",
    "government": "One-party state"
  },
  {
    "code": "CYP",
    "iso2": "CY",
    "name": "Cyprus",
    "continent": "Europe",
    "region": "Southern Europe",
    "population": 1189265,
    "landlocked": false,
    "areaKm2": 9251,
    "religion": "Christianity",
    "government": "Republic"
  },
  {
    "code": "CZE",
    "iso2": "CZ",
    "name": "Czechia",
    "continent": "Europe",
    "region": "Central Europe",
    "population": 10629928,
    "landlocked": true,
    "areaKm2": 78866,
    "religion": "Unaffiliated",
    "government": "Republic"
  },
  {
    "code": "DNK",
    "iso2": "DK",
    "name": "Denmark",
    "continent": "Europe",
    "region": "Northern Europe",
    "population": 5793636,
    "landlocked": false,
    "areaKm2": 43094,
    "religion": "Christianity",
    "government": "Constitutional monarchy"
  },
  {
    "code": "DJI",
    "iso2": "DJ",
    "name": "Djibouti",
    "continent": "Africa",
    "region": "Eastern Africa",
    "population": 958920,
    "landlocked": false,
    "areaKm2": 23200,
    "religion": "Islam",
    "government": "Republic"
  },
  {
    "code": "DMA",
    "iso2": "DM",
    "name": "Dominica",
    "continent": "Americas",
    "region": "Caribbean",
    "population": 71625,
    "landlocked": false,
    "areaKm2": 751,
    "religion": "Christianity",
    "government": "Republic"
  },
  {
    "code": "DOM",
    "iso2": "DO",
    "name": "Dominican Republic",
    "continent": "Americas",
    "region": "Caribbean",
    "population": 10627165,
    "landlocked": false,
    "areaKm2": 48511,
    "religion": "Christianity",
    "government": "Republic"
  },
  {
    "code": "COD",
    "iso2": "CD",
    "name": "DR Congo",
    "continent": "Africa",
    "region": "Middle Africa",
    "population": 84068091,
    "landlocked": false,
    "areaKm2": 2344858,
    "religion": "Christianity",
    "government": "Republic"
  },
  {
    "code": "ECU",
    "iso2": "EC",
    "name": "Ecuador",
    "continent": "Americas",
    "region": "South America",
    "population": 17084357,
    "landlocked": false,
    "areaKm2": 283561,
    "religion": "Christianity",
    "government": "Republic"
  },
  {
    "code": "EGY",
    "iso2": "EG",
    "name": "Egypt",
    "continent": "Africa",
    "region": "Northern Africa",
    "population": 98423595,
    "landlocked": false,
    "areaKm2": 1001449,
    "religion": "Islam",
    "government": "Republic"
  },
  {
    "code": "SLV",
    "iso2": "SV",
    "name": "El Salvador",
    "continent": "Americas",
    "region": "Central America",
    "population": 6420744,
    "landlocked": false,
    "areaKm2": 21041,
    "religion": "Christianity",
    "government": "Republic"
  },
  {
    "code": "GNQ",
    "iso2": "GQ",
    "name": "Equatorial Guinea",
    "continent": "Africa",
    "region": "Middle Africa",
    "population": 1308974,
    "landlocked": false,
    "areaKm2": 28051,
    "religion": "Christianity",
    "government": "Republic"
  },
  {
    "code": "ERI",
    "iso2": "ER",
    "name": "Eritrea",
    "continent": "Africa",
    "region": "Eastern Africa",
    "population": 6213972,
    "landlocked": false,
    "areaKm2": 117600,
    "religion": "Christianity",
    "government": "One-party state"
  },
  {
    "code": "EST",
    "iso2": "EE",
    "name": "Estonia",
    "continent": "Europe",
    "region": "Northern Europe",
    "population": 1321977,
    "landlocked": false,
    "areaKm2": 45227,
    "religion": "Unaffiliated",
    "government": "Republic"
  },
  {
    "code": "SWZ",
    "iso2": "SZ",
    "name": "Eswatini",
    "continent": "Africa",
    "region": "Southern Africa",
    "population": 1136191,
    "landlocked": true,
    "areaKm2": 17364,
    "religion": "Christianity",
    "government": "Monarchy"
  },
  {
    "code": "ETH",
    "iso2": "ET",
    "name": "Ethiopia",
    "continent": "Africa",
    "region": "Eastern Africa",
    "population": 109224559,
    "landlocked": true,
    "areaKm2": 1104300,
    "religion": "Christianity",
    "government": "Federal republic"
  },
  {
    "code": "FJI",
    "iso2": "FJ",
    "name": "Fiji",
    "continent": "Oceania",
    "region": "Melanesia",
    "population": 883483,
    "landlocked": false,
    "areaKm2": 18274,
    "religion": "Christianity",
    "government": "Republic"
  },
  {
    "code": "FIN",
    "iso2": "FI",
    "name": "Finland",
    "continent": "Europe",
    "region": "Northern Europe",
    "population": 5515525,
    "landlocked": false,
    "areaKm2": 338145,
    "religion": "Christianity",
    "government": "Republic"
  },
  {
    "code": "FRA",
    "iso2": "FR",
    "name": "France",
    "continent": "Europe",
    "region": "Western Europe",
    "population": 66977107,
    "landlocked": false,
    "areaKm2": 551500,
    "religion": "Christianity",
    "government": "Republic"
  },
  {
    "code": "GAB",
    "iso2": "GA",
    "name": "Gabon",
    "continent": "Africa",
    "region": "Middle Africa",
    "population": 2119275,
    "landlocked": false,
    "areaKm2": 267668,
    "religion": "Christianity",
    "government": "Republic"
  },
  {
    "code": "GMB",
    "iso2": "GM",
    "name": "Gambia",
    "continent": "Africa",
    "region": "Western Africa",
    "population": 2280102,
    "landlocked": false,
    "areaKm2": 11295,
    "religion": "Islam",
    "government": "Republic"
  },
  {
    "code": "GEO",
    "iso2": "GE",
    "name": "Georgia",
    "continent": "Asia",
    "region": "Western Asia",
    "population": 3726549,
    "landlocked": false,
    "areaKm2": 69700,
    "religion": "Islam",
    "government": "Republic"
  },
  {
    "code": "DEU",
    "iso2": "DE",
    "name": "Germany",
    "continent": "Europe",
    "region": "Western Europe",
    "population": 82905782,
    "landlocked": false,
    "areaKm2": 357022,
    "religion": "Christianity",
    "government": "Federal republic"
  },
  {
    "code": "GHA",
    "iso2": "GH",
    "name": "Ghana",
    "continent": "Africa",
    "region": "Western Africa",
    "population": 29767108,
    "landlocked": false,
    "areaKm2": 238533,
    "religion": "Christianity",
    "government": "Republic"
  },
  {
    "code": "GRC",
    "iso2": "GR",
    "name": "Greece",
    "continent": "Europe",
    "region": "Southern Europe",
    "population": 10731726,
    "landlocked": false,
    "areaKm2": 131626,
    "religion": "Christianity",
    "government": "Republic"
  },
  {
    "code": "GRD",
    "iso2": "GD",
    "name": "Grenada",
    "continent": "Americas",
    "region": "Caribbean",
    "population": 111454,
    "landlocked": false,
    "areaKm2": 344,
    "religion": "Christianity",
    "government": "Constitutional monarchy"
  },
  {
    "code": "GTM",
    "iso2": "GT",
    "name": "Guatemala",
    "continent": "Americas",
    "region": "Central America",
    "population": 17247807,
    "landlocked": false,
    "areaKm2": 108889,
    "religion": "Christianity",
    "government": "Republic"
  },
  {
    "code": "GIN",
    "iso2": "GN",
    "name": "Guinea",
    "continent": "Africa",
    "region": "Western Africa",
    "population": 12414318,
    "landlocked": false,
    "areaKm2": 245857,
    "religion": "Islam",
    "government": "Republic"
  },
  {
    "code": "GNB",
    "iso2": "GW",
    "name": "Guinea-Bissau",
    "continent": "Africa",
    "region": "Western Africa",
    "population": 1874309,
    "landlocked": false,
    "areaKm2": 36125,
    "religion": "Christianity",
    "government": "Republic"
  },
  {
    "code": "GUY",
    "iso2": "GY",
    "name": "Guyana",
    "continent": "Americas",
    "region": "South America",
    "population": 779004,
    "landlocked": false,
    "areaKm2": 214969,
    "religion": "Christianity",
    "government": "Republic"
  },
  {
    "code": "HTI",
    "iso2": "HT",
    "name": "Haiti",
    "continent": "Americas",
    "region": "Caribbean",
    "population": 11123176,
    "landlocked": false,
    "areaKm2": 27750,
    "religion": "Folk/Traditional",
    "government": "Republic"
  },
  {
    "code": "HND",
    "iso2": "HN",
    "name": "Honduras",
    "continent": "Americas",
    "region": "Central America",
    "population": 9587522,
    "landlocked": false,
    "areaKm2": 112088,
    "religion": "Christianity",
    "government": "Republic"
  },
  {
    "code": "HUN",
    "iso2": "HU",
    "name": "Hungary",
    "continent": "Europe",
    "region": "Central Europe",
    "population": 9775564,
    "landlocked": true,
    "areaKm2": 93030,
    "religion": "Christianity",
    "government": "Republic"
  },
  {
    "code": "ISL",
    "iso2": "IS",
    "name": "Iceland",
    "continent": "Europe",
    "region": "Northern Europe",
    "population": 352721,
    "landlocked": false,
    "areaKm2": 103000,
    "religion": "Christianity",
    "government": "Republic"
  },
  {
    "code": "IND",
    "iso2": "IN",
    "name": "India",
    "continent": "Asia",
    "region": "Southern Asia",
    "population": 1352617328,
    "landlocked": false,
    "areaKm2": 3287263,
    "religion": "Hinduism",
    "government": "Federal republic"
  },
  {
    "code": "IDN",
    "iso2": "ID",
    "name": "Indonesia",
    "continent": "Asia",
    "region": "South-Eastern Asia",
    "population": 267663435,
    "landlocked": false,
    "areaKm2": 1904569,
    "religion": "Islam",
    "government": "Republic"
  },
  {
    "code": "IRN",
    "iso2": "IR",
    "name": "Iran",
    "continent": "Asia",
    "region": "Southern Asia",
    "population": 81800269,
    "landlocked": false,
    "areaKm2": 1648195,
    "religion": "Islam",
    "government": "Theocracy"
  },
  {
    "code": "IRQ",
    "iso2": "IQ",
    "name": "Iraq",
    "continent": "Asia",
    "region": "Western Asia",
    "population": 38433600,
    "landlocked": false,
    "areaKm2": 438317,
    "religion": "Islam",
    "government": "Federal republic"
  },
  {
    "code": "IRL",
    "iso2": "IE",
    "name": "Ireland",
    "continent": "Europe",
    "region": "Northern Europe",
    "population": 4867309,
    "landlocked": false,
    "areaKm2": 70273,
    "religion": "Christianity",
    "government": "Republic"
  },
  {
    "code": "ISR",
    "iso2": "IL",
    "name": "Israel",
    "continent": "Asia",
    "region": "Western Asia",
    "population": 8882800,
    "landlocked": false,
    "areaKm2": 21056,
    "religion": "Judaism",
    "government": "Republic"
  },
  {
    "code": "ITA",
    "iso2": "IT",
    "name": "Italy",
    "continent": "Europe",
    "region": "Southern Europe",
    "population": 60421760,
    "landlocked": false,
    "areaKm2": 301316,
    "religion": "Christianity",
    "government": "Republic"
  },
  {
    "code": "CIV",
    "iso2": "CI",
    "name": "Ivory Coast",
    "continent": "Africa",
    "region": "Western Africa",
    "population": 25069229,
    "landlocked": false,
    "areaKm2": 322463,
    "religion": "Christianity",
    "government": "Republic"
  },
  {
    "code": "JAM",
    "iso2": "JM",
    "name": "Jamaica",
    "continent": "Americas",
    "region": "Caribbean",
    "population": 2934855,
    "landlocked": false,
    "areaKm2": 10990,
    "religion": "Christianity",
    "government": "Constitutional monarchy"
  },
  {
    "code": "JPN",
    "iso2": "JP",
    "name": "Japan",
    "continent": "Asia",
    "region": "Eastern Asia",
    "population": 126529100,
    "landlocked": false,
    "areaKm2": 377829,
    "religion": "Unaffiliated",
    "government": "Constitutional monarchy"
  },
  {
    "code": "JOR",
    "iso2": "JO",
    "name": "Jordan",
    "continent": "Asia",
    "region": "Western Asia",
    "population": 9956011,
    "landlocked": false,
    "areaKm2": 88946,
    "religion": "Islam",
    "government": "Monarchy"
  },
  {
    "code": "KAZ",
    "iso2": "KZ",
    "name": "Kazakhstan",
    "continent": "Asia",
    "region": "Central Asia",
    "population": 18272430,
    "landlocked": true,
    "areaKm2": 2724900,
    "religion": "Islam",
    "government": "Republic"
  },
  {
    "code": "KEN",
    "iso2": "KE",
    "name": "Kenya",
    "continent": "Africa",
    "region": "Eastern Africa",
    "population": 51393010,
    "landlocked": false,
    "areaKm2": 580367,
    "religion": "Christianity",
    "government": "Republic"
  },
  {
    "code": "KIR",
    "iso2": "KI",
    "name": "Kiribati",
    "continent": "Oceania",
    "region": "Micronesia",
    "population": 115847,
    "landlocked": false,
    "areaKm2": 726,
    "religion": "Christianity",
    "government": "Republic"
  },
  {
    "code": "KWT",
    "iso2": "KW",
    "name": "Kuwait",
    "continent": "Asia",
    "region": "Western Asia",
    "population": 4137309,
    "landlocked": false,
    "areaKm2": 17818,
    "religion": "Islam",
    "government": "Monarchy"
  },
  {
    "code": "KGZ",
    "iso2": "KG",
    "name": "Kyrgyzstan",
    "continent": "Asia",
    "region": "Central Asia",
    "population": 6322800,
    "landlocked": true,
    "areaKm2": 199900,
    "religion": "Islam",
    "government": "Republic"
  },
  {
    "code": "LAO",
    "iso2": "LA",
    "name": "Laos",
    "continent": "Asia",
    "region": "South-Eastern Asia",
    "population": 7061507,
    "landlocked": true,
    "areaKm2": 236800,
    "religion": "Buddhism",
    "government": "One-party state"
  },
  {
    "code": "LVA",
    "iso2": "LV",
    "name": "Latvia",
    "continent": "Europe",
    "region": "Northern Europe",
    "population": 1927174,
    "landlocked": false,
    "areaKm2": 64589,
    "religion": "Christianity",
    "government": "Republic"
  },
  {
    "code": "LBN",
    "iso2": "LB",
    "name": "Lebanon",
    "continent": "Asia",
    "region": "Western Asia",
    "population": 6848925,
    "landlocked": false,
    "areaKm2": 10400,
    "religion": "Islam",
    "government": "Republic"
  },
  {
    "code": "LSO",
    "iso2": "LS",
    "name": "Lesotho",
    "continent": "Africa",
    "region": "Southern Africa",
    "population": 2108132,
    "landlocked": true,
    "areaKm2": 30355,
    "religion": "Christianity",
    "government": "Constitutional monarchy"
  },
  {
    "code": "LBR",
    "iso2": "LR",
    "name": "Liberia",
    "continent": "Africa",
    "region": "Western Africa",
    "population": 4818977,
    "landlocked": false,
    "areaKm2": 111369,
    "religion": "Christianity",
    "government": "Republic"
  },
  {
    "code": "LBY",
    "iso2": "LY",
    "name": "Libya",
    "continent": "Africa",
    "region": "Northern Africa",
    "population": 6678567,
    "landlocked": false,
    "areaKm2": 1759540,
    "religion": "Islam",
    "government": "Republic"
  },
  {
    "code": "LIE",
    "iso2": "LI",
    "name": "Liechtenstein",
    "continent": "Europe",
    "region": "Western Europe",
    "population": 37910,
    "landlocked": true,
    "areaKm2": 160,
    "religion": "Christianity",
    "government": "Monarchy"
  },
  {
    "code": "LTU",
    "iso2": "LT",
    "name": "Lithuania",
    "continent": "Europe",
    "region": "Northern Europe",
    "population": 2801543,
    "landlocked": false,
    "areaKm2": 65301,
    "religion": "Christianity",
    "government": "Republic"
  },
  {
    "code": "LUX",
    "iso2": "LU",
    "name": "Luxembourg",
    "continent": "Europe",
    "region": "Western Europe",
    "population": 607950,
    "landlocked": true,
    "areaKm2": 2586,
    "religion": "Christianity",
    "government": "Constitutional monarchy"
  },
  {
    "code": "MDG",
    "iso2": "MG",
    "name": "Madagascar",
    "continent": "Africa",
    "region": "Eastern Africa",
    "population": 26262368,
    "landlocked": false,
    "areaKm2": 587041,
    "religion": "Christianity",
    "government": "Republic"
  },
  {
    "code": "MWI",
    "iso2": "MW",
    "name": "Malawi",
    "continent": "Africa",
    "region": "Eastern Africa",
    "population": 18143315,
    "landlocked": true,
    "areaKm2": 118484,
    "religion": "Christianity",
    "government": "Republic"
  },
  {
    "code": "MYS",
    "iso2": "MY",
    "name": "Malaysia",
    "continent": "Asia",
    "region": "South-Eastern Asia",
    "population": 31528585,
    "landlocked": false,
    "areaKm2": 329758,
    "religion": "Islam",
    "government": "Constitutional monarchy"
  },
  {
    "code": "MDV",
    "iso2": "MV",
    "name": "Maldives",
    "continent": "Asia",
    "region": "Southern Asia",
    "population": 515696,
    "landlocked": false,
    "areaKm2": 298,
    "religion": "Islam",
    "government": "Republic"
  },
  {
    "code": "MLI",
    "iso2": "ML",
    "name": "Mali",
    "continent": "Africa",
    "region": "Western Africa",
    "population": 19077690,
    "landlocked": true,
    "areaKm2": 1240192,
    "religion": "Islam",
    "government": "Republic"
  },
  {
    "code": "MLT",
    "iso2": "MT",
    "name": "Malta",
    "continent": "Europe",
    "region": "Southern Europe",
    "population": 484630,
    "landlocked": false,
    "areaKm2": 316,
    "religion": "Christianity",
    "government": "Republic"
  },
  {
    "code": "MHL",
    "iso2": "MH",
    "name": "Marshall Islands",
    "continent": "Oceania",
    "region": "Micronesia",
    "population": 58413,
    "landlocked": false,
    "areaKm2": 181,
    "religion": "Christianity",
    "government": "Republic"
  },
  {
    "code": "MRT",
    "iso2": "MR",
    "name": "Mauritania",
    "continent": "Africa",
    "region": "Western Africa",
    "population": 4403319,
    "landlocked": false,
    "areaKm2": 1025520,
    "religion": "Islam",
    "government": "Republic"
  },
  {
    "code": "MUS",
    "iso2": "MU",
    "name": "Mauritius",
    "continent": "Africa",
    "region": "Eastern Africa",
    "population": 1265303,
    "landlocked": false,
    "areaKm2": 2040,
    "religion": "Hinduism",
    "government": "Republic"
  },
  {
    "code": "MEX",
    "iso2": "MX",
    "name": "Mexico",
    "continent": "Americas",
    "region": "North America",
    "population": 126190788,
    "landlocked": false,
    "areaKm2": 1958201,
    "religion": "Christianity",
    "government": "Federal republic"
  },
  {
    "code": "FSM",
    "iso2": "FM",
    "name": "Micronesia",
    "continent": "Oceania",
    "region": "Micronesia",
    "population": 112640,
    "landlocked": false,
    "areaKm2": 702,
    "religion": "Christianity",
    "government": "Federal republic"
  },
  {
    "code": "MDA",
    "iso2": "MD",
    "name": "Moldova",
    "continent": "Europe",
    "region": "Eastern Europe",
    "population": 2706049,
    "landlocked": true,
    "areaKm2": 33851,
    "religion": "Christianity",
    "government": "Republic"
  },
  {
    "code": "MCO",
    "iso2": "MC",
    "name": "Monaco",
    "continent": "Europe",
    "region": "Western Europe",
    "population": 38682,
    "landlocked": false,
    "areaKm2": 2,
    "religion": "Christianity",
    "government": "Monarchy"
  },
  {
    "code": "MNG",
    "iso2": "MN",
    "name": "Mongolia",
    "continent": "Asia",
    "region": "Eastern Asia",
    "population": 3170208,
    "landlocked": true,
    "areaKm2": 1566500,
    "religion": "Buddhism",
    "government": "Republic"
  },
  {
    "code": "MNE",
    "iso2": "ME",
    "name": "Montenegro",
    "continent": "Europe",
    "region": "Southeast Europe",
    "population": 631219,
    "landlocked": false,
    "areaKm2": 13812,
    "religion": "Christianity",
    "government": "Republic"
  },
  {
    "code": "MAR",
    "iso2": "MA",
    "name": "Morocco",
    "continent": "Africa",
    "region": "Northern Africa",
    "population": 36029138,
    "landlocked": false,
    "areaKm2": 446550,
    "religion": "Islam",
    "government": "Monarchy"
  },
  {
    "code": "MOZ",
    "iso2": "MZ",
    "name": "Mozambique",
    "continent": "Africa",
    "region": "Eastern Africa",
    "population": 29495962,
    "landlocked": false,
    "areaKm2": 801590,
    "religion": "Christianity",
    "government": "Republic"
  },
  {
    "code": "MMR",
    "iso2": "MM",
    "name": "Myanmar",
    "continent": "Asia",
    "region": "South-Eastern Asia",
    "population": 53708395,
    "landlocked": false,
    "areaKm2": 676578,
    "religion": "Buddhism",
    "government": "Military junta"
  },
  {
    "code": "NAM",
    "iso2": "NA",
    "name": "Namibia",
    "continent": "Africa",
    "region": "Southern Africa",
    "population": 2448255,
    "landlocked": false,
    "areaKm2": 824292,
    "religion": "Christianity",
    "government": "Republic"
  },
  {
    "code": "NRU",
    "iso2": "NR",
    "name": "Nauru",
    "continent": "Oceania",
    "region": "Micronesia",
    "population": 12704,
    "landlocked": false,
    "areaKm2": 21,
    "religion": "Christianity",
    "government": "Republic"
  },
  {
    "code": "NPL",
    "iso2": "NP",
    "name": "Nepal",
    "continent": "Asia",
    "region": "Southern Asia",
    "population": 28087871,
    "landlocked": true,
    "areaKm2": 147181,
    "religion": "Hinduism",
    "government": "Federal republic"
  },
  {
    "code": "NLD",
    "iso2": "NL",
    "name": "Netherlands",
    "continent": "Europe",
    "region": "Western Europe",
    "population": 17231624,
    "landlocked": false,
    "areaKm2": 41526,
    "religion": "Christianity",
    "government": "Constitutional monarchy"
  },
  {
    "code": "NZL",
    "iso2": "NZ",
    "name": "New Zealand",
    "continent": "Oceania",
    "region": "Australia and New Zealand",
    "population": 4841000,
    "landlocked": false,
    "areaKm2": 270534,
    "religion": "Christianity",
    "government": "Constitutional monarchy"
  },
  {
    "code": "NIC",
    "iso2": "NI",
    "name": "Nicaragua",
    "continent": "Americas",
    "region": "Central America",
    "population": 6465513,
    "landlocked": false,
    "areaKm2": 130000,
    "religion": "Christianity",
    "government": "Republic"
  },
  {
    "code": "NER",
    "iso2": "NE",
    "name": "Niger",
    "continent": "Africa",
    "region": "Western Africa",
    "population": 22442948,
    "landlocked": true,
    "areaKm2": 1267000,
    "religion": "Islam",
    "government": "Republic"
  },
  {
    "code": "NGA",
    "iso2": "NG",
    "name": "Nigeria",
    "continent": "Africa",
    "region": "Western Africa",
    "population": 195874740,
    "landlocked": false,
    "areaKm2": 923768,
    "religion": "Christianity",
    "government": "Federal republic"
  },
  {
    "code": "PRK",
    "iso2": "KP",
    "name": "North Korea",
    "continent": "Asia",
    "region": "Eastern Asia",
    "population": 25549819,
    "landlocked": false,
    "areaKm2": 120538,
    "religion": "Unaffiliated",
    "government": "One-party state"
  },
  {
    "code": "MKD",
    "iso2": "MK",
    "name": "North Macedonia",
    "continent": "Europe",
    "region": "Southeast Europe",
    "population": 2084367,
    "landlocked": true,
    "areaKm2": 25713,
    "religion": "Christianity",
    "government": "Republic"
  },
  {
    "code": "NOR",
    "iso2": "NO",
    "name": "Norway",
    "continent": "Europe",
    "region": "Northern Europe",
    "population": 5311916,
    "landlocked": false,
    "areaKm2": 323877,
    "religion": "Christianity",
    "government": "Constitutional monarchy"
  },
  {
    "code": "OMN",
    "iso2": "OM",
    "name": "Oman",
    "continent": "Asia",
    "region": "Western Asia",
    "population": 4829483,
    "landlocked": false,
    "areaKm2": 309500,
    "religion": "Islam",
    "government": "Monarchy"
  },
  {
    "code": "PAK",
    "iso2": "PK",
    "name": "Pakistan",
    "continent": "Asia",
    "region": "Southern Asia",
    "population": 212215030,
    "landlocked": false,
    "areaKm2": 796095,
    "religion": "Islam",
    "government": "Federal republic"
  },
  {
    "code": "PLW",
    "iso2": "PW",
    "name": "Palau",
    "continent": "Oceania",
    "region": "Micronesia",
    "population": 17907,
    "landlocked": false,
    "areaKm2": 459,
    "religion": "Christianity",
    "government": "Republic"
  },
  {
    "code": "PAN",
    "iso2": "PA",
    "name": "Panama",
    "continent": "Americas",
    "region": "Central America",
    "population": 4176873,
    "landlocked": false,
    "areaKm2": 75517,
    "religion": "Christianity",
    "government": "Republic"
  },
  {
    "code": "PNG",
    "iso2": "PG",
    "name": "Papua New Guinea",
    "continent": "Oceania",
    "region": "Melanesia",
    "population": 8606316,
    "landlocked": false,
    "areaKm2": 462840,
    "religion": "Christianity",
    "government": "Constitutional monarchy"
  },
  {
    "code": "PRY",
    "iso2": "PY",
    "name": "Paraguay",
    "continent": "Americas",
    "region": "South America",
    "population": 6956071,
    "landlocked": true,
    "areaKm2": 406752,
    "religion": "Christianity",
    "government": "Republic"
  },
  {
    "code": "PER",
    "iso2": "PE",
    "name": "Peru",
    "continent": "Americas",
    "region": "South America",
    "population": 31989256,
    "landlocked": false,
    "areaKm2": 1285216,
    "religion": "Christianity",
    "government": "Republic"
  },
  {
    "code": "PHL",
    "iso2": "PH",
    "name": "Philippines",
    "continent": "Asia",
    "region": "South-Eastern Asia",
    "population": 106651922,
    "landlocked": false,
    "areaKm2": 300000,
    "religion": "Islam",
    "government": "Republic"
  },
  {
    "code": "POL",
    "iso2": "PL",
    "name": "Poland",
    "continent": "Europe",
    "region": "Central Europe",
    "population": 37974750,
    "landlocked": false,
    "areaKm2": 323250,
    "religion": "Christianity",
    "government": "Republic"
  },
  {
    "code": "PRT",
    "iso2": "PT",
    "name": "Portugal",
    "continent": "Europe",
    "region": "Southern Europe",
    "population": 10283822,
    "landlocked": false,
    "areaKm2": 91982,
    "religion": "Christianity",
    "government": "Republic"
  },
  {
    "code": "QAT",
    "iso2": "QA",
    "name": "Qatar",
    "continent": "Asia",
    "region": "Western Asia",
    "population": 2781677,
    "landlocked": false,
    "areaKm2": 11000,
    "religion": "Islam",
    "government": "Monarchy"
  },
  {
    "code": "ROU",
    "iso2": "RO",
    "name": "Romania",
    "continent": "Europe",
    "region": "Southeast Europe",
    "population": 19466145,
    "landlocked": false,
    "areaKm2": 238391,
    "religion": "Christianity",
    "government": "Republic"
  },
  {
    "code": "RUS",
    "iso2": "RU",
    "name": "Russia",
    "continent": "Europe",
    "region": "Eastern Europe",
    "population": 144478050,
    "landlocked": false,
    "areaKm2": 17075400,
    "religion": "Christianity",
    "government": "Federal republic"
  },
  {
    "code": "RWA",
    "iso2": "RW",
    "name": "Rwanda",
    "continent": "Africa",
    "region": "Eastern Africa",
    "population": 12301939,
    "landlocked": true,
    "areaKm2": 26338,
    "religion": "Christianity",
    "government": "Republic"
  },
  {
    "code": "KNA",
    "iso2": "KN",
    "name": "Saint Kitts and Nevis",
    "continent": "Americas",
    "region": "Caribbean",
    "population": 52441,
    "landlocked": false,
    "areaKm2": 261,
    "religion": "Christianity",
    "government": "Constitutional monarchy"
  },
  {
    "code": "LCA",
    "iso2": "LC",
    "name": "Saint Lucia",
    "continent": "Americas",
    "region": "Caribbean",
    "population": 181889,
    "landlocked": false,
    "areaKm2": 622,
    "religion": "Christianity",
    "government": "Constitutional monarchy"
  },
  {
    "code": "VCT",
    "iso2": "VC",
    "name": "Saint Vincent and the Grenadines",
    "continent": "Americas",
    "region": "Caribbean",
    "population": 110210,
    "landlocked": false,
    "areaKm2": 388,
    "religion": "Christianity",
    "government": "Constitutional monarchy"
  },
  {
    "code": "WSM",
    "iso2": "WS",
    "name": "Samoa",
    "continent": "Oceania",
    "region": "Polynesia",
    "population": 196130,
    "landlocked": false,
    "areaKm2": 2831,
    "religion": "Christianity",
    "government": "Republic"
  },
  {
    "code": "SMR",
    "iso2": "SM",
    "name": "San Marino",
    "continent": "Europe",
    "region": "Southern Europe",
    "population": 33785,
    "landlocked": true,
    "areaKm2": 61,
    "religion": "Christianity",
    "government": "Republic"
  },
  {
    "code": "STP",
    "iso2": "ST",
    "name": "São Tomé and Príncipe",
    "continent": "Africa",
    "region": "Middle Africa",
    "population": 211028,
    "landlocked": false,
    "areaKm2": 964,
    "religion": "Christianity",
    "government": "Republic"
  },
  {
    "code": "SAU",
    "iso2": "SA",
    "name": "Saudi Arabia",
    "continent": "Asia",
    "region": "Western Asia",
    "population": 33699947,
    "landlocked": false,
    "areaKm2": 2149690,
    "religion": "Islam",
    "government": "Monarchy"
  },
  {
    "code": "SEN",
    "iso2": "SN",
    "name": "Senegal",
    "continent": "Africa",
    "region": "Western Africa",
    "population": 15854360,
    "landlocked": false,
    "areaKm2": 196722,
    "religion": "Islam",
    "government": "Republic"
  },
  {
    "code": "SRB",
    "iso2": "RS",
    "name": "Serbia",
    "continent": "Europe",
    "region": "Southeast Europe",
    "population": 6963764,
    "landlocked": true,
    "areaKm2": 88361,
    "religion": "Christianity",
    "government": "Republic"
  },
  {
    "code": "SYC",
    "iso2": "SC",
    "name": "Seychelles",
    "continent": "Africa",
    "region": "Eastern Africa",
    "population": 96762,
    "landlocked": false,
    "areaKm2": 455,
    "religion": "Christianity",
    "government": "Republic"
  },
  {
    "code": "SLE",
    "iso2": "SL",
    "name": "Sierra Leone",
    "continent": "Africa",
    "region": "Western Africa",
    "population": 7650154,
    "landlocked": false,
    "areaKm2": 71740,
    "religion": "Islam",
    "government": "Republic"
  },
  {
    "code": "SGP",
    "iso2": "SG",
    "name": "Singapore",
    "continent": "Asia",
    "region": "South-Eastern Asia",
    "population": 5638676,
    "landlocked": false,
    "areaKm2": 618,
    "religion": "Mixed",
    "government": "Republic"
  },
  {
    "code": "SVK",
    "iso2": "SK",
    "name": "Slovakia",
    "continent": "Europe",
    "region": "Central Europe",
    "population": 5446771,
    "landlocked": true,
    "areaKm2": 49012,
    "religion": "Christianity",
    "government": "Republic"
  },
  {
    "code": "SVN",
    "iso2": "SI",
    "name": "Slovenia",
    "continent": "Europe",
    "region": "Central Europe",
    "population": 2073894,
    "landlocked": false,
    "areaKm2": 20256,
    "religion": "Christianity",
    "government": "Republic"
  },
  {
    "code": "SLB",
    "iso2": "SB",
    "name": "Solomon Islands",
    "continent": "Oceania",
    "region": "Melanesia",
    "population": 652858,
    "landlocked": false,
    "areaKm2": 28896,
    "religion": "Christianity",
    "government": "Constitutional monarchy"
  },
  {
    "code": "SOM",
    "iso2": "SO",
    "name": "Somalia",
    "continent": "Africa",
    "region": "Eastern Africa",
    "population": 15008154,
    "landlocked": false,
    "areaKm2": 637657,
    "religion": "Islam",
    "government": "Federal republic"
  },
  {
    "code": "ZAF",
    "iso2": "ZA",
    "name": "South Africa",
    "continent": "Africa",
    "region": "Southern Africa",
    "population": 57779622,
    "landlocked": false,
    "areaKm2": 1221037,
    "religion": "Christianity",
    "government": "Republic"
  },
  {
    "code": "KOR",
    "iso2": "KR",
    "name": "South Korea",
    "continent": "Asia",
    "region": "Eastern Asia",
    "population": 51606633,
    "landlocked": false,
    "areaKm2": 99434,
    "religion": "Mixed",
    "government": "Republic"
  },
  {
    "code": "SSD",
    "iso2": "SS",
    "name": "South Sudan",
    "continent": "Africa",
    "region": "Middle Africa",
    "population": 10975920,
    "landlocked": true,
    "areaKm2": 619745,
    "religion": "Christianity",
    "government": "Federal republic"
  },
  {
    "code": "ESP",
    "iso2": "ES",
    "name": "Spain",
    "continent": "Europe",
    "region": "Southern Europe",
    "population": 46796540,
    "landlocked": false,
    "areaKm2": 505992,
    "religion": "Christianity",
    "government": "Constitutional monarchy"
  },
  {
    "code": "LKA",
    "iso2": "LK",
    "name": "Sri Lanka",
    "continent": "Asia",
    "region": "Southern Asia",
    "population": 21670000,
    "landlocked": false,
    "areaKm2": 65610,
    "religion": "Buddhism",
    "government": "Republic"
  },
  {
    "code": "SDN",
    "iso2": "SD",
    "name": "Sudan",
    "continent": "Africa",
    "region": "Northern Africa",
    "population": 41801533,
    "landlocked": false,
    "areaKm2": 1886068,
    "religion": "Islam",
    "government": "Federal republic"
  },
  {
    "code": "SUR",
    "iso2": "SR",
    "name": "Suriname",
    "continent": "Americas",
    "region": "South America",
    "population": 575991,
    "landlocked": false,
    "areaKm2": 163265,
    "religion": "Mixed",
    "government": "Republic"
  },
  {
    "code": "SWE",
    "iso2": "SE",
    "name": "Sweden",
    "continent": "Europe",
    "region": "Northern Europe",
    "population": 10175214,
    "landlocked": false,
    "areaKm2": 449964,
    "religion": "Christianity",
    "government": "Constitutional monarchy"
  },
  {
    "code": "CHE",
    "iso2": "CH",
    "name": "Switzerland",
    "continent": "Europe",
    "region": "Western Europe",
    "population": 8513227,
    "landlocked": true,
    "areaKm2": 41284,
    "religion": "Christianity",
    "government": "Federal republic"
  },
  {
    "code": "SYR",
    "iso2": "SY",
    "name": "Syria",
    "continent": "Asia",
    "region": "Western Asia",
    "population": 16906283,
    "landlocked": false,
    "areaKm2": 185180,
    "religion": "Islam",
    "government": "Republic"
  },
  {
    "code": "TWN",
    "iso2": "TW",
    "name": "Taiwan",
    "continent": "Asia",
    "region": "Eastern Asia",
    "population": 23570000,
    "landlocked": false,
    "areaKm2": 36193,
    "religion": "Mixed",
    "government": "Republic"
  },
  {
    "code": "TJK",
    "iso2": "TJ",
    "name": "Tajikistan",
    "continent": "Asia",
    "region": "Central Asia",
    "population": 9100837,
    "landlocked": true,
    "areaKm2": 143100,
    "religion": "Islam",
    "government": "Republic"
  },
  {
    "code": "TZA",
    "iso2": "TZ",
    "name": "Tanzania",
    "continent": "Africa",
    "region": "Eastern Africa",
    "population": 56318348,
    "landlocked": false,
    "areaKm2": 883749,
    "religion": "Christianity",
    "government": "Republic"
  },
  {
    "code": "THA",
    "iso2": "TH",
    "name": "Thailand",
    "continent": "Asia",
    "region": "South-Eastern Asia",
    "population": 69428524,
    "landlocked": false,
    "areaKm2": 513115,
    "religion": "Buddhism",
    "government": "Constitutional monarchy"
  },
  {
    "code": "TLS",
    "iso2": "TL",
    "name": "Timor-Leste",
    "continent": "Asia",
    "region": "South-Eastern Asia",
    "population": 1267972,
    "landlocked": false,
    "areaKm2": 14874,
    "religion": "Islam",
    "government": "Republic"
  },
  {
    "code": "TGO",
    "iso2": "TG",
    "name": "Togo",
    "continent": "Africa",
    "region": "Western Africa",
    "population": 7889094,
    "landlocked": false,
    "areaKm2": 56785,
    "religion": "Folk/Traditional",
    "government": "Republic"
  },
  {
    "code": "TON",
    "iso2": "TO",
    "name": "Tonga",
    "continent": "Oceania",
    "region": "Polynesia",
    "population": 103197,
    "landlocked": false,
    "areaKm2": 650,
    "religion": "Christianity",
    "government": "Monarchy"
  },
  {
    "code": "TTO",
    "iso2": "TT",
    "name": "Trinidad and Tobago",
    "continent": "Americas",
    "region": "Caribbean",
    "population": 1389858,
    "landlocked": false,
    "areaKm2": 5130,
    "religion": "Christianity",
    "government": "Republic"
  },
  {
    "code": "TUN",
    "iso2": "TN",
    "name": "Tunisia",
    "continent": "Africa",
    "region": "Northern Africa",
    "population": 11565204,
    "landlocked": false,
    "areaKm2": 163610,
    "religion": "Islam",
    "government": "Republic"
  },
  {
    "code": "TUR",
    "iso2": "TR",
    "name": "Türkiye",
    "continent": "Asia",
    "region": "Western Asia",
    "population": 82319724,
    "landlocked": false,
    "areaKm2": 774815,
    "religion": "Islam",
    "government": "Republic"
  },
  {
    "code": "TKM",
    "iso2": "TM",
    "name": "Turkmenistan",
    "continent": "Asia",
    "region": "Central Asia",
    "population": 5850908,
    "landlocked": true,
    "areaKm2": 488100,
    "religion": "Islam",
    "government": "Republic"
  },
  {
    "code": "TUV",
    "iso2": "TV",
    "name": "Tuvalu",
    "continent": "Oceania",
    "region": "Polynesia",
    "population": 11508,
    "landlocked": false,
    "areaKm2": 26,
    "religion": "Christianity",
    "government": "Constitutional monarchy"
  },
  {
    "code": "UGA",
    "iso2": "UG",
    "name": "Uganda",
    "continent": "Africa",
    "region": "Eastern Africa",
    "population": 42723139,
    "landlocked": true,
    "areaKm2": 241038,
    "religion": "Christianity",
    "government": "Republic"
  },
  {
    "code": "UKR",
    "iso2": "UA",
    "name": "Ukraine",
    "continent": "Europe",
    "region": "Eastern Europe",
    "population": 44622516,
    "landlocked": false,
    "areaKm2": 603700,
    "religion": "Christianity",
    "government": "Republic"
  },
  {
    "code": "ARE",
    "iso2": "AE",
    "name": "United Arab Emirates",
    "continent": "Asia",
    "region": "Western Asia",
    "population": 9630959,
    "landlocked": false,
    "areaKm2": 83600,
    "religion": "Islam",
    "government": "Monarchy"
  },
  {
    "code": "GBR",
    "iso2": "GB",
    "name": "United Kingdom",
    "continent": "Europe",
    "region": "Northern Europe",
    "population": 66460344,
    "landlocked": false,
    "areaKm2": 242900,
    "religion": "Christianity",
    "government": "Constitutional monarchy"
  },
  {
    "code": "USA",
    "iso2": "US",
    "name": "United States",
    "continent": "Americas",
    "region": "North America",
    "population": 326687501,
    "landlocked": false,
    "areaKm2": 9363520,
    "religion": "Christianity",
    "government": "Federal republic"
  },
  {
    "code": "URY",
    "iso2": "UY",
    "name": "Uruguay",
    "continent": "Americas",
    "region": "South America",
    "population": 3449299,
    "landlocked": false,
    "areaKm2": 175016,
    "religion": "Christianity",
    "government": "Republic"
  },
  {
    "code": "UZB",
    "iso2": "UZ",
    "name": "Uzbekistan",
    "continent": "Asia",
    "region": "Central Asia",
    "population": 32955400,
    "landlocked": true,
    "areaKm2": 447400,
    "religion": "Islam",
    "government": "Republic"
  },
  {
    "code": "VUT",
    "iso2": "VU",
    "name": "Vanuatu",
    "continent": "Oceania",
    "region": "Melanesia",
    "population": 292680,
    "landlocked": false,
    "areaKm2": 12189,
    "religion": "Christianity",
    "government": "Republic"
  },
  {
    "code": "VAT",
    "iso2": "VA",
    "name": "Vatican City",
    "continent": "Europe",
    "region": "Southern Europe",
    "population": 825,
    "landlocked": true,
    "areaKm2": 0,
    "religion": "Christianity",
    "government": "Theocracy"
  },
  {
    "code": "VEN",
    "iso2": "VE",
    "name": "Venezuela",
    "continent": "Americas",
    "region": "South America",
    "population": 28870195,
    "landlocked": false,
    "areaKm2": 912050,
    "religion": "Christianity",
    "government": "Federal republic"
  },
  {
    "code": "VNM",
    "iso2": "VN",
    "name": "Vietnam",
    "continent": "Asia",
    "region": "South-Eastern Asia",
    "population": 95540395,
    "landlocked": false,
    "areaKm2": 331689,
    "religion": "Unaffiliated",
    "government": "One-party state"
  },
  {
    "code": "YEM",
    "iso2": "YE",
    "name": "Yemen",
    "continent": "Asia",
    "region": "Western Asia",
    "population": 28498687,
    "landlocked": false,
    "areaKm2": 527968,
    "religion": "Islam",
    "government": "Republic"
  },
  {
    "code": "ZMB",
    "iso2": "ZM",
    "name": "Zambia",
    "continent": "Africa",
    "region": "Eastern Africa",
    "population": 17351822,
    "landlocked": true,
    "areaKm2": 752618,
    "religion": "Christianity",
    "government": "Republic"
  },
  {
    "code": "ZWE",
    "iso2": "ZW",
    "name": "Zimbabwe",
    "continent": "Africa",
    "region": "Eastern Africa",
    "population": 14439018,
    "landlocked": true,
    "areaKm2": 390757,
    "religion": "Christianity",
    "government": "Republic"
  }
] as const satisfies readonly CountryFact[];
