//! The daily-puzzle helpers production's Wordle, Geodle, Flaggle and Travle share
//! (`desktop/src/lib/{wordle,geodle,flaggle,travle}.ts` each carry an identical copy).
//!
//! A puzzle is a pure function of `(local date, seed salt)`: the salt is a random UUID made once
//! per profile (`makeWordleSeedSalt` & co.) and stored with the puzzle, so every user gets their
//! own daily order, but the same user always gets the same answer for a given day. The salt is
//! generated by the caller (the app crate), never here.

/// `hashString`: FNV-1a (32-bit) over the string's UTF-16 code units, exactly as JavaScript's
/// `charCodeAt` walks it, with `Math.imul` wrapping.
pub fn hash_string(value: &str) -> u32 {
    let mut hash: u32 = 2_166_136_261;
    for unit in value.encode_utf16() {
        hash ^= u32::from(unit);
        hash = hash.wrapping_mul(16_777_619);
    }
    hash
}

/// `FIRST_PUZZLE_DATE` of every daily game.
pub const FIRST_PUZZLE_DATE: &str = "2026-01-01";

/// `new Date("<date>T00:00:00Z")` in whole days since the Unix epoch, or `None` where V8 returns
/// an invalid date. V8 accepts any day 01-31 in any month and rolls the excess over (so
/// `2026-02-30` is March 2nd); it rejects a month outside 01-12, a day outside 01-31 and anything
/// that is not `YYYY-MM-DD`.
pub fn js_utc_day_number(date: &str) -> Option<i64> {
    let bytes = date.as_bytes();
    if bytes.len() != 10 || bytes[4] != b'-' || bytes[7] != b'-' {
        return None;
    }
    let digits = |range: std::ops::Range<usize>| -> Option<i64> {
        let text = date.get(range)?;
        if !text.bytes().all(|b| b.is_ascii_digit()) {
            return None;
        }
        text.parse().ok()
    };
    let (year, month, day) = (digits(0..4)?, digits(5..7)?, digits(8..10)?);
    if !(1..=12).contains(&month) || !(1..=31).contains(&day) {
        return None;
    }
    // Hinnant's days_from_civil is linear in `day`, which is exactly V8's roll-over.
    let y = if month <= 2 { year - 1 } else { year };
    let era = y.div_euclid(400);
    let yoe = y - era * 400;
    let mp = (month + 9) % 12;
    let doy = (153 * mp + 2) / 5 + day - 1;
    let doe = yoe * 365 + yoe / 4 - yoe / 100 + doy;
    Some(era * 146_097 + doe - 719_468)
}

/// `daysSinceFirstPuzzle`: whole days from 2026-01-01, never negative; an unparsable date is 0
/// (`Number.isFinite(NaN)` fails, so production returns 0).
pub fn days_since_first_puzzle(date: &str) -> u64 {
    let start = js_utc_day_number(FIRST_PUZZLE_DATE).expect("constant date");
    match js_utc_day_number(date) {
        Some(target) => (target - start).max(0) as u64,
        None => 0,
    }
}

/// `Number.prototype.toString(36)` for a non-negative integer.
pub fn to_base36(mut value: u32) -> String {
    if value == 0 {
        return "0".into();
    }
    let mut digits = Vec::new();
    while value > 0 {
        let digit = (value % 36) as u8;
        digits.push(if digit < 10 {
            b'0' + digit
        } else {
            b'a' + digit - 10
        });
        value /= 36;
    }
    digits.reverse();
    String::from_utf8(digits).expect("ascii")
}

/// `get*PuzzleId`: `"<date>:<hash(salt) in base 36>"`.
pub fn puzzle_id(date: &str, seed_salt: &str) -> String {
    format!("{date}:{}", to_base36(hash_string(seed_salt)))
}

/// The answer index production picks for `date`: it maps every item to
/// `hashString("<salt>:<key>:<index>")`, sorts by that (a stable sort, so ties keep list order),
/// and takes position `daysSinceFirstPuzzle(date) % len`. Selecting the n-th smallest
/// `(hash, index)` pair is the same order without sorting the whole list.
pub fn daily_index<'a>(
    keys: impl ExactSizeIterator<Item = &'a str>,
    seed_salt: &str,
    date: &str,
) -> usize {
    let mut keyed: Vec<(u32, usize)> = keys
        .enumerate()
        .map(|(index, key)| (hash_string(&format!("{seed_salt}:{key}:{index}")), index))
        .collect();
    assert!(!keyed.is_empty(), "a daily game needs at least one answer");
    let nth = (days_since_first_puzzle(date) % keyed.len() as u64) as usize;
    let (_, picked, _) = keyed.select_nth_unstable(nth);
    picked.1
}
